'use client'

import { useEffect, useState } from 'react'
import { useParams } from 'next/navigation'
import { CalendarDays, CheckCircle2, ChevronDown, Flag, Layers3, Pencil, Plus, Trash2 } from 'lucide-react'
import { Button } from '@/components/common/Button'
import { Input } from '@/components/common/Input'
import { Modal } from '@/components/common/Modal'
import { ErrorState, LoadingState } from '@/components/common/PageState'
import { usePhaseImpact, useWBS, useWBSActions } from '@/features/wbs/hooks/useWBS'
import { useProjectDetail } from '@/features/projects/hooks/useProjects'
import { formatDate, formatStatus } from '@/lib/format'
import { getApiErrorMessage } from '@/types/api.types'
import type { Epic, Milestone, Phase, Sprint } from '@/types/wbs.types'

type Editor =
  | { kind: 'phase'; item?: Phase }
  | { kind: 'sprint'; phaseId: number; item?: Sprint }
  | { kind: 'epic'; item?: Epic }
  | { kind: 'milestone'; item?: Milestone }

export default function WBSPage() {
  const projectId = Number(useParams<{ id: string }>().id)
  const query = useWBS(projectId)
  const projectQuery = useProjectDetail(projectId)
  const actions = useWBSActions(projectId)
  const [editor, setEditor] = useState<Editor | null>(null)
  const [deleting, setDeleting] = useState<Phase | null>(null)
  if (query.isLoading) return <LoadingState label="Loading work breakdown…" />
  if (query.isError || !query.data) return <ErrorState message={getApiErrorMessage(query.error)} />
  const wbs = query.data
  const canManage = Boolean(projectQuery.data?.current_user_role === 'PM' || projectQuery.data?.capabilities.can_update)
  const confirmDelete = (label: string, mutation: () => void) => { if (window.confirm(`Delete ${label}? Linked tasks will be kept and unlinked.`)) mutation() }
  return <div className="space-y-6">
    <header className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-2xl font-semibold">Work breakdown</h2><p className="text-sm text-muted-foreground">Organize phases, sprints, epics and milestones.</p></div>{canManage && <div className="flex flex-wrap gap-2"><Button className="w-auto" onClick={() => setEditor({ kind: 'phase' })}><Plus className="h-4 w-4" />Phase</Button><Button variant="outline" className="w-auto" onClick={() => setEditor({ kind: 'epic' })}><Plus className="h-4 w-4" />Epic</Button><Button variant="outline" className="w-auto" onClick={() => setEditor({ kind: 'milestone' })}><Plus className="h-4 w-4" />Milestone</Button></div>}</header>
    <section className="space-y-4"><div className="flex items-center gap-2"><Layers3 className="h-5 w-5 text-primary" /><h3 className="text-lg font-semibold">Phases</h3></div>{wbs.phases.length === 0 && <Empty label="No phases yet." />}{wbs.phases.map(phase => <details key={phase.id} open className="rounded-xl border bg-card"><summary className="flex cursor-pointer list-none items-center justify-between gap-3 p-4"><div><div className="flex items-center gap-2"><ChevronDown className="h-4 w-4" /><strong>{phase.name}</strong><Badge>{formatStatus(phase.status)}</Badge></div><p className="mt-1 text-xs text-muted-foreground">{formatDate(phase.start_date)} – {formatDate(phase.end_date)} · {phase.tasks.length + phase.sprints.reduce((sum, sprint) => sum + sprint.tasks.length, 0)} tasks</p></div>{canManage && <div className="flex gap-1" onClick={event => event.preventDefault()}><IconButton label="Edit phase" onClick={() => setEditor({ kind: 'phase', item: phase })}><Pencil className="h-4 w-4" /></IconButton><IconButton label="Add sprint" onClick={() => setEditor({ kind: 'sprint', phaseId: phase.id })}><Plus className="h-4 w-4" /></IconButton><IconButton label="Delete phase" onClick={() => setDeleting(phase)} destructive><Trash2 className="h-4 w-4" /></IconButton></div>}</summary><div className="grid gap-3 border-t p-4 lg:grid-cols-2">{phase.sprints.map(sprint => <div key={sprint.id} className="rounded-lg border p-3"><div className="flex items-start justify-between gap-2"><div><strong className="text-sm">{sprint.name}</strong><p className="text-xs text-muted-foreground">{formatStatus(sprint.status)} · {sprint.tasks.length} tasks · {sprint.story_points_completed}/{sprint.story_points_committed} pts</p></div>{canManage && <div className="flex"><IconButton label="Edit sprint" onClick={() => setEditor({ kind: 'sprint', phaseId: phase.id, item: sprint })}><Pencil className="h-4 w-4" /></IconButton><IconButton label="Delete sprint" destructive onClick={() => confirmDelete(sprint.name, () => actions.deleteSprint.mutate(sprint.id))}><Trash2 className="h-4 w-4" /></IconButton></div>}</div>{canManage && <div className="mt-2 flex gap-2">{sprint.status === 'PLANNED' && <Button variant="outline" className="min-h-9 w-auto px-3 py-1 text-xs" onClick={() => actions.startSprint.mutate(sprint.id)}>Start</Button>}{sprint.status === 'ACTIVE' && <Button variant="outline" className="min-h-9 w-auto px-3 py-1 text-xs" onClick={() => actions.completeSprint.mutate(sprint.id)}>Complete</Button>}</div>}</div>)}{phase.sprints.length === 0 && <Empty label="No sprints in this phase." />}</div></details>)}</section>
    {wbs.unphased_sprints.length > 0 && <section><h3 className="mb-3 font-semibold">Unphased sprints</h3><div className="grid gap-3 md:grid-cols-2">{wbs.unphased_sprints.map(sprint => <div key={sprint.id} className="rounded-lg border p-3"><strong>{sprint.name}</strong><p className="text-xs text-muted-foreground">{sprint.tasks.length} tasks</p></div>)}</div></section>}
    <div className="grid gap-6 xl:grid-cols-2"><section className="rounded-xl border bg-card p-5"><div className="mb-4 flex items-center gap-2"><Flag className="h-5 w-5 text-primary" /><h3 className="font-semibold">Epics</h3></div><div className="space-y-2">{wbs.epics.length === 0 && <Empty label="No epics yet." />}{wbs.epics.map(epic => <div key={epic.id} className="flex items-center justify-between rounded-lg border p-3"><div className="flex items-center gap-3"><span className="h-3 w-3 rounded-full" style={{ background: epic.color || '#64748b' }} /><div><strong className="text-sm">{epic.name}</strong><p className="text-xs text-muted-foreground">{formatStatus(epic.status)}</p></div></div>{canManage && <div className="flex"><IconButton label="Edit epic" onClick={() => setEditor({ kind: 'epic', item: epic })}><Pencil className="h-4 w-4" /></IconButton><IconButton label="Delete epic" destructive onClick={() => confirmDelete(epic.name, () => actions.deleteEpic.mutate(epic.id))}><Trash2 className="h-4 w-4" /></IconButton></div>}</div>)}</div></section><section className="rounded-xl border bg-card p-5"><div className="mb-4 flex items-center gap-2"><CalendarDays className="h-5 w-5 text-primary" /><h3 className="font-semibold">Milestones</h3></div><div className="space-y-2">{wbs.milestones.length === 0 && <Empty label="No milestones yet." />}{wbs.milestones.map(milestone => <div key={milestone.id} className="flex items-center justify-between rounded-lg border p-3"><div><strong className="text-sm">{milestone.name}</strong><p className="text-xs text-muted-foreground">{formatDate(milestone.due_date)} · {formatStatus(milestone.status)}</p></div>{canManage && <div className="flex">{milestone.status !== 'COMPLETED' && <IconButton label="Complete milestone" onClick={() => actions.completeMilestone.mutate(milestone.id)}><CheckCircle2 className="h-4 w-4" /></IconButton>}<IconButton label="Edit milestone" onClick={() => setEditor({ kind: 'milestone', item: milestone })}><Pencil className="h-4 w-4" /></IconButton><IconButton label="Delete milestone" destructive onClick={() => confirmDelete(milestone.name, () => actions.deleteMilestone.mutate(milestone.id))}><Trash2 className="h-4 w-4" /></IconButton></div>}</div>)}</div></section></div>
    <EntityEditor editor={editor} onClose={() => setEditor(null)} actions={actions} />
    <DeletePhaseDialog phase={deleting} phases={wbs.phases} onClose={() => setDeleting(null)} onDelete={(strategy, targetPhaseId) => actions.deletePhase.mutate({ id: deleting!.id, strategy, targetPhaseId }, { onSuccess: () => setDeleting(null) })} isLoading={actions.deletePhase.isPending} />
  </div>
}

function EntityEditor({ editor, onClose, actions }: { editor: Editor | null; onClose: () => void; actions: ReturnType<typeof useWBSActions> }) {
  const [form, setForm] = useState<Record<string, string>>({})
  useEffect(() => { if (!editor) return; const item = editor.item; setForm({ name: item?.name || '', description: 'description' in (item || {}) ? String((item as Epic | Milestone | Phase).description || '') : '', goal: 'goal' in (item || {}) ? String((item as Sprint).goal || '') : '', start_date: 'start_date' in (item || {}) ? String((item as Phase | Sprint).start_date || '') : '', end_date: 'end_date' in (item || {}) ? String((item as Phase | Sprint).end_date || '') : '', due_date: 'due_date' in (item || {}) ? String((item as Milestone).due_date || '') : '', color: 'color' in (item || {}) ? String((item as Epic).color || '#3b82f6') : '#3b82f6', status: item?.status || '' }) }, [editor])
  if (!editor) return null
  const submit = (event: React.FormEvent) => { event.preventDefault(); const cleaned = Object.fromEntries(Object.entries(form).map(([key, value]) => [key, value || null])); const done = { onSuccess: onClose }
    if (editor.kind === 'phase') editor.item ? actions.updatePhase.mutate({ id: editor.item.id, body: cleaned }, done) : actions.createPhase.mutate(cleaned as never, done)
    if (editor.kind === 'sprint') editor.item ? actions.updateSprint.mutate({ id: editor.item.id, body: cleaned }, done) : actions.createSprint.mutate({ phaseId: editor.phaseId, body: cleaned as never }, done)
    if (editor.kind === 'epic') editor.item ? actions.updateEpic.mutate({ id: editor.item.id, body: cleaned }, done) : actions.createEpic.mutate(cleaned as never, done)
    if (editor.kind === 'milestone') editor.item ? actions.updateMilestone.mutate({ id: editor.item.id, body: cleaned }, done) : actions.createMilestone.mutate(cleaned as never, done)
  }
  const pending = Object.values(actions).some(value => 'isPending' in value && value.isPending)
  return <Modal open onClose={onClose} title={`${editor.item ? 'Edit' : 'New'} ${editor.kind}`}><form className="space-y-4" onSubmit={submit}><Field label="Name"><Input required minLength={3} value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></Field>{editor.kind === 'sprint' ? <Field label="Goal"><textarea className="min-h-24 w-full rounded-md border bg-background p-3" value={form.goal || ''} onChange={e => setForm({ ...form, goal: e.target.value })} /></Field> : <Field label="Description"><textarea className="min-h-24 w-full rounded-md border bg-background p-3" value={form.description || ''} onChange={e => setForm({ ...form, description: e.target.value })} /></Field>}{(editor.kind === 'phase' || editor.kind === 'sprint') && <div className="grid gap-4 sm:grid-cols-2"><Field label="Start date"><Input type="date" value={form.start_date || ''} onChange={e => setForm({ ...form, start_date: e.target.value })} /></Field><Field label="End date"><Input type="date" value={form.end_date || ''} onChange={e => setForm({ ...form, end_date: e.target.value })} /></Field></div>}{editor.kind === 'milestone' && <Field label="Due date"><Input type="date" value={form.due_date || ''} onChange={e => setForm({ ...form, due_date: e.target.value })} /></Field>}{editor.kind === 'epic' && <Field label="Color"><Input type="color" value={form.color || '#3b82f6'} onChange={e => setForm({ ...form, color: e.target.value })} /></Field>}{editor.item && <Field label="Status"><select className="h-11 w-full rounded-md border bg-background px-3" value={form.status || ''} onChange={e => setForm({ ...form, status: e.target.value })}>{statusOptions(editor.kind).map(status => <option key={status}>{status}</option>)}</select></Field>}<div className="flex justify-end gap-2"><Button type="button" variant="outline" className="w-auto" onClick={onClose}>Cancel</Button><Button type="submit" className="w-auto" isLoading={pending}>Save</Button></div></form></Modal>
}

function DeletePhaseDialog({ phase, phases, onClose, onDelete, isLoading }: { phase: Phase | null; phases: Phase[]; onClose: () => void; onDelete: (strategy: 'cascade' | 'reassign' | 'unlink', target?: number) => void; isLoading: boolean }) {
  const impact = usePhaseImpact(phase?.id ?? null)
  const [strategy, setStrategy] = useState<'cascade' | 'reassign' | 'unlink'>('unlink')
  const [target, setTarget] = useState('')
  const [confirmation, setConfirmation] = useState('')
  useEffect(() => { setStrategy('unlink'); setTarget(''); setConfirmation('') }, [phase])
  if (!phase) return null
  const canSubmit = strategy !== 'reassign' ? strategy !== 'cascade' || confirmation === phase.name : Boolean(target)
  return <Modal open onClose={onClose} title={`Delete ${phase.name}`} description="Review the live impact before choosing how child work should be handled.">{impact.isLoading ? <LoadingState label="Calculating impact…" /> : impact.data && <div className="space-y-5"><div className="grid grid-cols-2 gap-2 text-sm sm:grid-cols-3">{Object.entries({ Sprints: impact.data.sprint_count, Tasks: impact.data.task_count, Subtasks: impact.data.subtask_count, 'External links': impact.data.external_dependency_count, Assignments: impact.data.assignment_count, Worklogs: impact.data.worklog_count }).map(([label, value]) => <div key={label} className="rounded-lg border p-3"><strong>{value}</strong><p className="text-xs text-muted-foreground">{label}</p></div>)}</div><Field label="Strategy"><select className="h-11 w-full rounded-md border bg-background px-3" value={strategy} onChange={e => setStrategy(e.target.value as typeof strategy)}><option value="unlink">Keep children and unlink</option><option value="reassign">Move to another phase</option><option value="cascade">Delete the entire tree</option></select></Field>{strategy === 'reassign' && <Field label="Target phase"><select required className="h-11 w-full rounded-md border bg-background px-3" value={target} onChange={e => setTarget(e.target.value)}><option value="">Select phase…</option>{phases.filter(item => item.id !== phase.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field>}{strategy === 'cascade' && <div className="rounded-lg border border-destructive/40 bg-destructive/5 p-4"><p className="text-sm">Type <strong>{phase.name}</strong> to confirm permanent cascade deletion.</p><Input className="mt-3" value={confirmation} onChange={e => setConfirmation(e.target.value)} /></div>}<div className="flex justify-end gap-2"><Button variant="outline" className="w-auto" onClick={onClose}>Cancel</Button><Button variant="destructive" className="w-auto" disabled={!canSubmit} isLoading={isLoading} onClick={() => onDelete(strategy, target ? Number(target) : undefined)}>Delete phase</Button></div></div>}</Modal>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1.5 text-sm font-medium"><span>{label}</span>{children}</label> }
function Empty({ label }: { label: string }) { return <p className="rounded-lg border border-dashed p-4 text-center text-sm text-muted-foreground">{label}</p> }
function Badge({ children }: { children: React.ReactNode }) { return <span className="rounded-full bg-muted px-2 py-0.5 text-xs font-medium text-muted-foreground">{children}</span> }
function IconButton({ label, children, onClick, destructive = false }: { label: string; children: React.ReactNode; onClick: () => void; destructive?: boolean }) { return <button type="button" title={label} aria-label={label} onClick={onClick} className={`inline-flex h-10 w-10 items-center justify-center rounded-md hover:bg-accent ${destructive ? 'text-destructive' : 'text-muted-foreground hover:text-foreground'}`}>{children}</button> }
function statusOptions(kind: Editor['kind']) { return kind === 'phase' ? ['PLANNED', 'IN_PROGRESS', 'COMPLETED', 'ON_HOLD'] : kind === 'sprint' ? ['PLANNED', 'ACTIVE', 'COMPLETED', 'CANCELLED'] : kind === 'epic' ? ['OPEN', 'IN_PROGRESS', 'DONE', 'CLOSED'] : ['PENDING', 'AT_RISK', 'COMPLETED', 'MISSED'] }
