'use client'

import { useEffect, useMemo, useState } from 'react'
import { Clock3, Link2, Play, Plus, Square, Trash2, UserPlus } from 'lucide-react'
import { Button } from '@/components/common/Button'
import { Input } from '@/components/common/Input'
import { ConfirmDialog } from '@/components/common/ConfirmDialog'
import { Modal } from '@/components/common/Modal'
import { ErrorState, LoadingState } from '@/components/common/PageState'
import { useProjectMembers } from '@/features/projects/hooks/useProjectMembers'
import { useActiveTimer, useTask, useTaskActions, useWorklogs } from '@/features/tasks/hooks/useTasks'
import { useWBS } from '@/features/wbs/hooks/useWBS'
import { formatDate, formatStatus } from '@/lib/format'
import { getApiErrorMessage } from '@/types/api.types'
import type { Task, TaskPriority } from '@/types/task.types'
import { useAuthStore } from '@/store/authStore'

export function TaskDrawer({ projectId, taskId, allTasks, onClose }: { projectId: number; taskId: number | null; allTasks: Task[]; onClose: () => void }) {
  const query = useTask(taskId)
  const worklogs = useWorklogs(taskId)
  const timer = useActiveTimer()
  const wbs = useWBS(projectId)
  const members = useProjectMembers(projectId)
  const actions = useTaskActions(projectId)
  const currentUserId = useAuthStore(state => state.user?.id)
  const task = query.data
  const [form, setForm] = useState({ name: '', description: '', priority: 'MEDIUM' as TaskPriority, start_date: '', due_date: '', phase_id: '', sprint_id: '', epic_id: '', labels: '' })
  const [confirmingDelete, setConfirmingDelete] = useState(false)
  const [subtaskName, setSubtaskName] = useState('')
  const [dependencyTask, setDependencyTask] = useState('')
  const [dependencyType, setDependencyType] = useState('FS')
  const [assignUser, setAssignUser] = useState('')
  const [allocatedHours, setAllocatedHours] = useState('0')
  const [makePrimary, setMakePrimary] = useState(false)
  const [logHours, setLogHours] = useState('')
  const [logDescription, setLogDescription] = useState('')
  useEffect(() => { if (!task) return; setForm({ name: task.name, description: task.description || '', priority: task.priority, start_date: task.start_date || '', due_date: task.due_date || '', phase_id: task.phase_id?.toString() || '', sprint_id: task.sprint_id?.toString() || '', epic_id: task.epic_id?.toString() || '', labels: task.labels.join(', ') }) }, [task])
  const sprints = useMemo(() => [...(wbs.data?.phases.flatMap(phase => phase.sprints) || []), ...(wbs.data?.unphased_sprints || [])], [wbs.data])
  if (taskId === null) return null
  const save = (event: React.FormEvent) => { event.preventDefault(); actions.update.mutate({ id: taskId, body: { ...form, phase_id: form.phase_id ? Number(form.phase_id) : null, sprint_id: form.sprint_id ? Number(form.sprint_id) : null, epic_id: form.epic_id ? Number(form.epic_id) : null, labels: form.labels.split(',').map(label => label.trim()).filter(Boolean), start_date: form.start_date || null, due_date: form.due_date || null } }) }
  return <Modal open onClose={onClose} title={task?.name || 'Task details'} className="max-w-5xl">{query.isLoading ? <LoadingState label="Loading task…" /> : query.isError || !task ? <ErrorState message={getApiErrorMessage(query.error)} /> : <div className="grid gap-6 lg:grid-cols-[1.25fr_.75fr]">
    <div className="space-y-6"><form onSubmit={save} className="space-y-4"><div className="grid gap-4 sm:grid-cols-2"><Field label="Name"><Input disabled={!task.capabilities.can_update} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} /></Field><Field label="Priority"><select disabled={!task.capabilities.can_update} className="h-11 w-full rounded-md border bg-background px-3" value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value as TaskPriority })}>{['LOW', 'MEDIUM', 'HIGH', 'CRITICAL'].map(value => <option key={value}>{value}</option>)}</select></Field></div><Field label="Description"><textarea disabled={!task.capabilities.can_update} className="min-h-28 w-full rounded-md border bg-background p-3" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field><div className="grid gap-4 sm:grid-cols-3"><Field label="Phase"><select disabled={!task.capabilities.can_update} className="h-11 w-full rounded-md border bg-background px-3" value={form.phase_id} onChange={e => setForm({ ...form, phase_id: e.target.value, sprint_id: '' })}><option value="">Unphased</option>{wbs.data?.phases.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Sprint"><select disabled={!task.capabilities.can_update} className="h-11 w-full rounded-md border bg-background px-3" value={form.sprint_id} onChange={e => setForm({ ...form, sprint_id: e.target.value })}><option value="">Backlog</option>{sprints.filter(item => !form.phase_id || item.phase_id === Number(form.phase_id)).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Epic"><select disabled={!task.capabilities.can_update} className="h-11 w-full rounded-md border bg-background px-3" value={form.epic_id} onChange={e => setForm({ ...form, epic_id: e.target.value })}><option value="">No epic</option>{wbs.data?.epics.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><div className="grid gap-4 sm:grid-cols-2"><Field label="Start date"><Input disabled={!task.capabilities.can_update} type="date" value={form.start_date} onChange={e => setForm({ ...form, start_date: e.target.value })} /></Field><Field label="Due date"><Input disabled={!task.capabilities.can_update} type="date" value={form.due_date} onChange={e => setForm({ ...form, due_date: e.target.value })} /></Field></div><Field label="Labels"><Input disabled={!task.capabilities.can_update} placeholder="frontend, urgent" value={form.labels} onChange={e => setForm({ ...form, labels: e.target.value })} /></Field>{task.capabilities.can_update && <Button className="w-auto" type="submit" isLoading={actions.update.isPending}>Save task</Button>}</form>
      <Section title="Subtasks" icon={<Plus className="h-4 w-4" />}><div className="space-y-2">{task.subtasks.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg border p-3"><button className={`text-left text-sm ${item.is_completed ? 'line-through text-muted-foreground' : ''}`} onClick={() => actions.updateSubtask.mutate({ id: item.id, taskId, body: { status: item.is_completed ? 'TODO' : 'DONE' } })}>{item.name}</button><IconButton label="Delete subtask" onClick={() => actions.removeSubtask.mutate({ id: item.id, taskId })}><Trash2 className="h-4 w-4" /></IconButton></div>)}</div>{task.capabilities.can_change_status && <form className="mt-3 flex gap-2" onSubmit={e => { e.preventDefault(); if (subtaskName.trim()) actions.createSubtask.mutate({ taskId, body: { name: subtaskName.trim() } }, { onSuccess: () => setSubtaskName('') }) }}><Input placeholder="Add a subtask" value={subtaskName} onChange={e => setSubtaskName(e.target.value)} /><Button className="w-auto" type="submit">Add</Button></form>}</Section>
      <Section title="Dependencies" icon={<Link2 className="h-4 w-4" />}><div className="space-y-2">{task.predecessor_dependencies.map(dep => <div key={dep.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><span>{dep.predecessor_name} → {dep.dependency_type} {dep.lag_days ? `(${dep.lag_days}d)` : ''}</span>{task.capabilities.can_manage_dependencies && <IconButton label="Remove dependency" onClick={() => actions.removeDependency.mutate(dep.id)}><Trash2 className="h-4 w-4" /></IconButton>}</div>)}</div>{task.capabilities.can_manage_dependencies && <form className="mt-3 grid gap-2 sm:grid-cols-[1fr_90px_auto]" onSubmit={e => { e.preventDefault(); if (dependencyTask) actions.addDependency.mutate({ taskId, body: { depends_on_task_id: Number(dependencyTask), dependency_type: dependencyType, lag_days: 0 } }, { onSuccess: () => setDependencyTask('') }) }}><select required className="h-11 rounded-md border bg-background px-3" value={dependencyTask} onChange={e => setDependencyTask(e.target.value)}><option value="">Select predecessor…</option>{allTasks.filter(item => item.id !== task.id).map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select><select className="h-11 rounded-md border bg-background px-3" value={dependencyType} onChange={e => setDependencyType(e.target.value)}>{['FS', 'SS', 'FF', 'SF'].map(value => <option key={value}>{value}</option>)}</select><Button type="submit">Link</Button></form>}</Section>
    </div>
    <aside className="space-y-6"><section className="rounded-xl border bg-card p-4"><h3 className="font-semibold">Status</h3><select disabled={!task.capabilities.can_change_status} className="mt-3 h-11 w-full rounded-md border bg-background px-3" value={task.status} onChange={e => actions.changeStatus.mutate({ id: task.id, status: e.target.value as Task['status'] })}>{['TODO', 'IN_PROGRESS', 'IN_REVIEW', 'DONE', 'BLOCKED'].map(value => <option key={value}>{formatStatus(value)}</option>)}</select><dl className="mt-4 grid grid-cols-2 gap-3 text-xs"><Metric label="Logged" value={`${task.total_logged_hours.toFixed(1)}h`} /><Metric label="Estimate" value={`${task.estimated_hours ?? 0}h`} /><Metric label="Float" value={`${task.float_days ?? 0}d`} /><Metric label="Critical" value={task.is_critical ? 'Yes' : 'No'} /></dl></section>
      <Section title="Team" icon={<UserPlus className="h-4 w-4" />}><div className="space-y-2">{task.assignments.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><div><strong>{item.user?.full_name || `User #${item.user_id}`}</strong><p className="text-xs text-muted-foreground">{item.is_primary ? 'Primary · ' : ''}{item.allocated_hours}h</p></div>{task.capabilities.can_manage_assignments && <IconButton label="Unassign" onClick={() => actions.unassign.mutate(item.id)}><Trash2 className="h-4 w-4" /></IconButton>}</div>)}</div>{task.capabilities.can_manage_assignments && <form className="mt-3 space-y-2" onSubmit={e => { e.preventDefault(); if (assignUser) actions.assign.mutate({ taskId, body: { user_id: Number(assignUser), allocated_hours: Number(allocatedHours), is_primary: makePrimary } }, { onSuccess: () => { setAssignUser(''); setAllocatedHours('0'); setMakePrimary(false) } }) }}><select required className="h-11 w-full rounded-md border bg-background px-3" value={assignUser} onChange={e => setAssignUser(e.target.value)}><option value="">Select member…</option>{members.data?.filter(member => !task.assignments.some(item => item.user_id === member.user.id)).map(member => <option key={member.user.id} value={member.user.id}>{member.user.full_name}</option>)}</select><Input type="number" min="0" step="0.5" value={allocatedHours} onChange={e => setAllocatedHours(e.target.value)} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={makePrimary} onChange={e => setMakePrimary(e.target.checked)} />Primary assignee</label><Button type="submit" variant="outline">Assign</Button>{actions.assign.data?.warnings.map(warning => <p key={`${warning.date}-${warning.reason}`} className="rounded-md bg-amber-50 p-2 text-xs text-amber-800">{warning.date}: {warning.reason === 'on_leave' ? 'member is on approved leave' : `${warning.total_hours}h allocated`}</p>)}</form>}</Section>
      <Section title="Time tracking" icon={<Clock3 className="h-4 w-4" />}>{task.capabilities.can_log_work && <div className="mb-3">{timer.data ? <Button variant="outline" onClick={() => actions.stopTimer.mutate(timer.data!.id)} isLoading={actions.stopTimer.isPending}><Square className="h-4 w-4" />Stop timer</Button> : <Button variant="outline" onClick={() => actions.startTimer.mutate(task.id)} isLoading={actions.startTimer.isPending}><Play className="h-4 w-4" />Start work</Button>}</div>}<div className="space-y-2">{worklogs.data?.map(item => <div key={item.id} className="flex items-center justify-between rounded-lg border p-3 text-sm"><div><strong>{item.is_running ? 'Running' : `${item.hours.toFixed(2)}h`}</strong><p className="text-xs text-muted-foreground">{formatDate(item.log_date)} · {item.description || 'No note'}</p></div>{!item.is_running && item.user_id === currentUserId && <IconButton label="Delete worklog" onClick={() => actions.removeWorklog.mutate({ id: item.id, taskId })}><Trash2 className="h-4 w-4" /></IconButton>}</div>)}</div>{task.capabilities.can_log_work && <form className="mt-3 space-y-2" onSubmit={e => { e.preventDefault(); if (Number(logHours) > 0) actions.addWorklog.mutate({ taskId, body: { hours: Number(logHours), log_date: localDate(), description: logDescription } }, { onSuccess: () => { setLogHours(''); setLogDescription('') } }) }}><Input type="number" min="0.01" max="24" step="0.25" placeholder="Hours" value={logHours} onChange={e => setLogHours(e.target.value)} /><Input placeholder="What did you work on?" value={logDescription} onChange={e => setLogDescription(e.target.value)} /><Button type="submit" variant="outline">Log time</Button></form>}</Section>
      {task.capabilities.can_delete && <Button variant="destructive" onClick={() => setConfirmingDelete(true)} isLoading={actions.remove.isPending}><Trash2 className="h-4 w-4" />Delete task</Button>}
      <ConfirmDialog open={confirmingDelete} title={`Delete ${task.name}?`} description="This removes the task and its subtasks, worklogs and dependencies. It cannot be undone." confirmLabel="Delete task" isLoading={actions.remove.isPending} onConfirm={() => actions.remove.mutate(task.id, { onSuccess: () => { setConfirmingDelete(false); onClose() } })} onClose={() => setConfirmingDelete(false)} />
    </aside>
  </div>}</Modal>
}

function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="block space-y-1.5 text-sm font-medium"><span>{label}</span>{children}</label> }
function Section({ title, icon, children }: { title: string; icon: React.ReactNode; children: React.ReactNode }) { return <section className="rounded-xl border bg-card p-4"><div className="mb-3 flex items-center gap-2 text-primary">{icon}<h3 className="font-semibold text-foreground">{title}</h3></div>{children}</section> }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-md bg-muted p-2"><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-semibold text-foreground">{value}</dd></div> }
function IconButton({ label, onClick, children }: { label: string; onClick: () => void; children: React.ReactNode }) { return <button type="button" title={label} aria-label={label} onClick={onClick} className="inline-flex h-10 w-10 items-center justify-center rounded-md text-muted-foreground hover:bg-accent hover:text-destructive">{children}</button> }
function localDate() { const now = new Date(); return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, '0')}-${String(now.getDate()).padStart(2, '0')}` }
